[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/musics"
  to = "/"

[[redirects]]
  from = "/page:*"
  to = "/page/:splat"
